# Generated by Django 4.0.3 on 2022-03-23 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_referraluser_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraluser',
            name='inviter_referral_code',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
