# Generated by Django 4.0.3 on 2022-03-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_referraluser_inviter_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referraluser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
